-- Possum Crypto -- Database Schema

-- Every signal generated by a variant (BUY, SELL, or HOLD)
CREATE TABLE IF NOT EXISTS crypto_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp_utc TEXT NOT NULL,
    symbol TEXT NOT NULL,                   -- BTC/AUD, ETH/AUD, SOL/AUD
    variant TEXT NOT NULL,                  -- M1, M2, MR1, S1, etc.
    signal TEXT NOT NULL,                   -- buy, sell, hold
    confidence REAL,
    grok_direction TEXT,                    -- LONG, SHORT, FLAT
    grok_confidence REAL,
    regime TEXT,                            -- BULLISH, BEARISH, NEUTRAL, etc.
    fgi_value INTEGER,
    price_at_signal REAL,
    reasoning TEXT,
    executed INTEGER DEFAULT 0             -- 0=signal only, 1=trade placed
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol ON crypto_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_variant ON crypto_signals(variant);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON crypto_signals(timestamp_utc);

-- Regime state logged each run
CREATE TABLE IF NOT EXISTS crypto_regime_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp_utc TEXT NOT NULL,
    fgi_value INTEGER,
    fgi_label TEXT,
    regime TEXT,
    btc_dominance_pct REAL
);

-- Open positions tracked for stop/TP management
CREATE TABLE IF NOT EXISTS positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    variant TEXT NOT NULL,
    side TEXT NOT NULL,                     -- 'long' or 'short'
    entry_timestamp_utc TEXT NOT NULL,
    entry_price REAL NOT NULL,
    quantity REAL NOT NULL,
    stop_loss REAL NOT NULL,
    take_profit REAL NOT NULL,
    current_price REAL,
    unrealised_pnl_aud REAL,
    status TEXT DEFAULT 'open',            -- 'open', 'closed'
    close_timestamp_utc TEXT,
    close_price REAL,
    realised_pnl_aud REAL,
    close_reason TEXT,                     -- 'stop_loss', 'take_profit', 'manual', 'signal'
    dry_run INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_positions_status ON positions(status);

-- Completed trades for P&L tracking
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp_utc TEXT NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,                     -- 'buy' or 'sell'
    quantity REAL NOT NULL,
    price_aud REAL NOT NULL,
    notional_aud REAL,
    fee_aud REAL DEFAULT 0,
    variant TEXT NOT NULL,
    dry_run INTEGER DEFAULT 1
);

-- Daily P&L summary
CREATE TABLE IF NOT EXISTS daily_pnl (
    date TEXT PRIMARY KEY,
    starting_equity_aud REAL,
    ending_equity_aud REAL,
    realised_pnl_aud REAL,
    unrealised_pnl_aud REAL,
    trades_opened INTEGER DEFAULT 0,
    trades_closed INTEGER DEFAULT 0,
    win_count INTEGER DEFAULT 0,
    loss_count INTEGER DEFAULT 0
);

-- API cost tracking (shared pattern with US/AU)
CREATE TABLE IF NOT EXISTS api_costs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp_utc TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    estimated_cost_usd REAL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_api_costs_timestamp ON api_costs(timestamp_utc);
